// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_ListAgents_FullMethodName            = "/wackypub.agent.v1.AgentService/ListAgents"
	AgentService_InspectAgent_FullMethodName          = "/wackypub.agent.v1.AgentService/InspectAgent"
	AgentService_ReadSession_FullMethodName           = "/wackypub.agent.v1.AgentService/ReadSession"
	AgentService_ReadMemory_FullMethodName            = "/wackypub.agent.v1.AgentService/ReadMemory"
	AgentService_RenderSystemPrompt_FullMethodName    = "/wackypub.agent.v1.AgentService/RenderSystemPrompt"
	AgentService_InspectSessionContext_FullMethodName = "/wackypub.agent.v1.AgentService/InspectSessionContext"
	AgentService_InspectAgentLocks_FullMethodName     = "/wackypub.agent.v1.AgentService/InspectAgentLocks"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService defines the interface of record for WackyPub agent operations (D112).
//
// In v1, this interface is consumed strictly in-process through generated Go types
// and interfaces; no network transport (gRPC/HTTP), network listener, or remote daemon
// is deployed or required. The protobuf definition serves as the canonical contract
// defining operation semantics, data models, and migration boundaries for the WackyPub
// agent lifecycle.
//
// D112 establishes a unified 26-method service interface replacing the legacy monolithic
// AgentSDK methods across five staged rollout phases:
//   - Phase 1 (current): Read-only workspace queries and state inspection (7 methods:
//     ListAgents, InspectAgent, ReadSession, ReadMemory, RenderSystemPrompt,
//     InspectSessionContext, InspectAgentLocks).
//   - Phase 2: Mutation and session operations (e.g., prompt, generate, compact), including
//     streaming methods (Phase 2 canary).
//   - Phase 3: Scratchpad, attachments, and tool discovery operations.
//   - Phase 4: Side-effectful / background operations (e.g. git commit hooks, compaction runner path).
//   - Phase 5: Complete cutover and deprecation/removal of legacy SDK entry points.
//
// Design Decisions:
//   - Q1: Go code generation produces interface stubs (AgentServiceServer) embedded directly
//     into AgentSDK without network overhead.
//   - Q2: Protobuf service definitions are the sole source of truth for method signatures
//     and wire structures, replacing ad-hoc Go structs.
//   - Q5: Staged migration permits progressive implementation and contract testing while
//     keeping existing CLI workflows fully backward-compatible.
type AgentServiceClient interface {
	// ListAgents discovers and returns the identifiers of all agent directories present
	// directly under the specified workspace root. An agent directory is recognized if it
	// contains the marker file (AGENTS.md). Callers invoke this method during workspace
	// discovery, multi-agent orchestration, or status reporting. If the workspace directory
	// does not exist or contains no valid agent directories, an empty list is returned without error.
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// InspectAgent performs an extensive diagnostic audit of an agent directory's filesystem state.
	// Callers invoke this method to determine configuration completeness, file presence, allowlists,
	// discovered tools and skills, and session corruption statistics without triggering agent execution
	// or modifying on-disk state. This call intentionally avoids acquiring session locks to prevent
	// self-deadlocks when called by an agent inspecting itself mid-turn. If the target agent directory
	// does not exist, the response sets agent_dir_exists to false with all remaining fields zero-valued.
	InspectAgent(ctx context.Context, in *InspectAgentRequest, opts ...grpc.CallOption) (*InspectAgentResponse, error)
	// ReadSession reads and returns the full conversational turn history stored in the agent's
	// session.jsonl file. Callers use this method to inspect past user/model interactions, replay
	// conversations, or audit transcripts. In v1, turns and content parts are converted to SessionTurn
	// structures containing plain text and inline data; tool invocations (FunctionCall and FunctionResponse)
	// are omitted under accepted-lossy v1 conversion. If session.jsonl does not exist, an empty list
	// of turns is returned without error.
	ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...grpc.CallOption) (*ReadSessionResponse, error)
	// ReadMemory retrieves the raw markdown content of the agent's long-term memory notes from
	// MEMORY.md. Callers use this method to read persistent memories across sessions. Read access
	// is subject to workspace allowlist authorization against the target agent. If MEMORY.md does
	// not exist, an empty string is returned without error.
	ReadMemory(ctx context.Context, in *ReadMemoryRequest, opts ...grpc.CallOption) (*ReadMemoryResponse, error)
	// RenderSystemPrompt renders the agent's complete system prompt from AGENTS.md, expanding
	// any macro inclusion directives (@<FILE_PATH>) into their referenced file contents. Callers
	// use this method to view or feed the actual prompt passed to the model backend during generation.
	// Returns an error if AGENTS.md cannot be read or if cyclic macro references are detected.
	RenderSystemPrompt(ctx context.Context, in *RenderSystemPromptRequest, opts ...grpc.CallOption) (*RenderSystemPromptResponse, error)
	// InspectSessionContext calculates current token usage, context window limits, and auto-compaction
	// headroom for an agent per D93/D101. Callers invoke this method to monitor context window consumption,
	// plan proactive compaction, or display diagnostics. It estimates token counts across session turns,
	// the rendered system prompt, and memory files, returning headroom percentages and the most recent turn
	// token metrics if available.
	InspectSessionContext(ctx context.Context, in *InspectSessionContextRequest, opts ...grpc.CallOption) (*InspectSessionContextResponse, error)
	// InspectAgentLocks surveys all agent directories in the workspace and returns lock status and session
	// activity for each agent per D100. Callers invoke this method to detect active agent executions, identify
	// stale lock files left behind by dead processes, or debug concurrency contention. The lock file outlives
	// release, so lock presence alone does not imply held; callers must check holder_pid_valid, holder_alive,
	// and last_write.
	InspectAgentLocks(ctx context.Context, in *InspectAgentLocksRequest, opts ...grpc.CallOption) (*InspectAgentLocksResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InspectAgent(ctx context.Context, in *InspectAgentRequest, opts ...grpc.CallOption) (*InspectAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_InspectAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...grpc.CallOption) (*ReadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_ReadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReadMemory(ctx context.Context, in *ReadMemoryRequest, opts ...grpc.CallOption) (*ReadMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadMemoryResponse)
	err := c.cc.Invoke(ctx, AgentService_ReadMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RenderSystemPrompt(ctx context.Context, in *RenderSystemPromptRequest, opts ...grpc.CallOption) (*RenderSystemPromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderSystemPromptResponse)
	err := c.cc.Invoke(ctx, AgentService_RenderSystemPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InspectSessionContext(ctx context.Context, in *InspectSessionContextRequest, opts ...grpc.CallOption) (*InspectSessionContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectSessionContextResponse)
	err := c.cc.Invoke(ctx, AgentService_InspectSessionContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InspectAgentLocks(ctx context.Context, in *InspectAgentLocksRequest, opts ...grpc.CallOption) (*InspectAgentLocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectAgentLocksResponse)
	err := c.cc.Invoke(ctx, AgentService_InspectAgentLocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations should embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService defines the interface of record for WackyPub agent operations (D112).
//
// In v1, this interface is consumed strictly in-process through generated Go types
// and interfaces; no network transport (gRPC/HTTP), network listener, or remote daemon
// is deployed or required. The protobuf definition serves as the canonical contract
// defining operation semantics, data models, and migration boundaries for the WackyPub
// agent lifecycle.
//
// D112 establishes a unified 26-method service interface replacing the legacy monolithic
// AgentSDK methods across five staged rollout phases:
//   - Phase 1 (current): Read-only workspace queries and state inspection (7 methods:
//     ListAgents, InspectAgent, ReadSession, ReadMemory, RenderSystemPrompt,
//     InspectSessionContext, InspectAgentLocks).
//   - Phase 2: Mutation and session operations (e.g., prompt, generate, compact), including
//     streaming methods (Phase 2 canary).
//   - Phase 3: Scratchpad, attachments, and tool discovery operations.
//   - Phase 4: Side-effectful / background operations (e.g. git commit hooks, compaction runner path).
//   - Phase 5: Complete cutover and deprecation/removal of legacy SDK entry points.
//
// Design Decisions:
//   - Q1: Go code generation produces interface stubs (AgentServiceServer) embedded directly
//     into AgentSDK without network overhead.
//   - Q2: Protobuf service definitions are the sole source of truth for method signatures
//     and wire structures, replacing ad-hoc Go structs.
//   - Q5: Staged migration permits progressive implementation and contract testing while
//     keeping existing CLI workflows fully backward-compatible.
type AgentServiceServer interface {
	// ListAgents discovers and returns the identifiers of all agent directories present
	// directly under the specified workspace root. An agent directory is recognized if it
	// contains the marker file (AGENTS.md). Callers invoke this method during workspace
	// discovery, multi-agent orchestration, or status reporting. If the workspace directory
	// does not exist or contains no valid agent directories, an empty list is returned without error.
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// InspectAgent performs an extensive diagnostic audit of an agent directory's filesystem state.
	// Callers invoke this method to determine configuration completeness, file presence, allowlists,
	// discovered tools and skills, and session corruption statistics without triggering agent execution
	// or modifying on-disk state. This call intentionally avoids acquiring session locks to prevent
	// self-deadlocks when called by an agent inspecting itself mid-turn. If the target agent directory
	// does not exist, the response sets agent_dir_exists to false with all remaining fields zero-valued.
	InspectAgent(context.Context, *InspectAgentRequest) (*InspectAgentResponse, error)
	// ReadSession reads and returns the full conversational turn history stored in the agent's
	// session.jsonl file. Callers use this method to inspect past user/model interactions, replay
	// conversations, or audit transcripts. In v1, turns and content parts are converted to SessionTurn
	// structures containing plain text and inline data; tool invocations (FunctionCall and FunctionResponse)
	// are omitted under accepted-lossy v1 conversion. If session.jsonl does not exist, an empty list
	// of turns is returned without error.
	ReadSession(context.Context, *ReadSessionRequest) (*ReadSessionResponse, error)
	// ReadMemory retrieves the raw markdown content of the agent's long-term memory notes from
	// MEMORY.md. Callers use this method to read persistent memories across sessions. Read access
	// is subject to workspace allowlist authorization against the target agent. If MEMORY.md does
	// not exist, an empty string is returned without error.
	ReadMemory(context.Context, *ReadMemoryRequest) (*ReadMemoryResponse, error)
	// RenderSystemPrompt renders the agent's complete system prompt from AGENTS.md, expanding
	// any macro inclusion directives (@<FILE_PATH>) into their referenced file contents. Callers
	// use this method to view or feed the actual prompt passed to the model backend during generation.
	// Returns an error if AGENTS.md cannot be read or if cyclic macro references are detected.
	RenderSystemPrompt(context.Context, *RenderSystemPromptRequest) (*RenderSystemPromptResponse, error)
	// InspectSessionContext calculates current token usage, context window limits, and auto-compaction
	// headroom for an agent per D93/D101. Callers invoke this method to monitor context window consumption,
	// plan proactive compaction, or display diagnostics. It estimates token counts across session turns,
	// the rendered system prompt, and memory files, returning headroom percentages and the most recent turn
	// token metrics if available.
	InspectSessionContext(context.Context, *InspectSessionContextRequest) (*InspectSessionContextResponse, error)
	// InspectAgentLocks surveys all agent directories in the workspace and returns lock status and session
	// activity for each agent per D100. Callers invoke this method to detect active agent executions, identify
	// stale lock files left behind by dead processes, or debug concurrency contention. The lock file outlives
	// release, so lock presence alone does not imply held; callers must check holder_pid_valid, holder_alive,
	// and last_write.
	InspectAgentLocks(context.Context, *InspectAgentLocksRequest) (*InspectAgentLocksResponse, error)
}

// UnimplementedAgentServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentServiceServer) InspectAgent(context.Context, *InspectAgentRequest) (*InspectAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectAgent not implemented")
}
func (UnimplementedAgentServiceServer) ReadSession(context.Context, *ReadSessionRequest) (*ReadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadSession not implemented")
}
func (UnimplementedAgentServiceServer) ReadMemory(context.Context, *ReadMemoryRequest) (*ReadMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadMemory not implemented")
}
func (UnimplementedAgentServiceServer) RenderSystemPrompt(context.Context, *RenderSystemPromptRequest) (*RenderSystemPromptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderSystemPrompt not implemented")
}
func (UnimplementedAgentServiceServer) InspectSessionContext(context.Context, *InspectSessionContextRequest) (*InspectSessionContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectSessionContext not implemented")
}
func (UnimplementedAgentServiceServer) InspectAgentLocks(context.Context, *InspectAgentLocksRequest) (*InspectAgentLocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectAgentLocks not implemented")
}
func (UnimplementedAgentServiceServer) testEmbeddedByValue() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InspectAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InspectAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InspectAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InspectAgent(ctx, req.(*InspectAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReadSession(ctx, req.(*ReadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReadMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReadMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReadMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReadMemory(ctx, req.(*ReadMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RenderSystemPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderSystemPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RenderSystemPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RenderSystemPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RenderSystemPrompt(ctx, req.(*RenderSystemPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InspectSessionContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectSessionContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InspectSessionContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InspectSessionContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InspectSessionContext(ctx, req.(*InspectSessionContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InspectAgentLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectAgentLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InspectAgentLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InspectAgentLocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InspectAgentLocks(ctx, req.(*InspectAgentLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wackypub.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgents",
			Handler:    _AgentService_ListAgents_Handler,
		},
		{
			MethodName: "InspectAgent",
			Handler:    _AgentService_InspectAgent_Handler,
		},
		{
			MethodName: "ReadSession",
			Handler:    _AgentService_ReadSession_Handler,
		},
		{
			MethodName: "ReadMemory",
			Handler:    _AgentService_ReadMemory_Handler,
		},
		{
			MethodName: "RenderSystemPrompt",
			Handler:    _AgentService_RenderSystemPrompt_Handler,
		},
		{
			MethodName: "InspectSessionContext",
			Handler:    _AgentService_InspectSessionContext_Handler,
		},
		{
			MethodName: "InspectAgentLocks",
			Handler:    _AgentService_InspectAgentLocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
