// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_ListAgents_FullMethodName               = "/wackypub.agent.v1.AgentService/ListAgents"
	AgentService_InspectAgent_FullMethodName             = "/wackypub.agent.v1.AgentService/InspectAgent"
	AgentService_ReadSession_FullMethodName              = "/wackypub.agent.v1.AgentService/ReadSession"
	AgentService_ReadMemory_FullMethodName               = "/wackypub.agent.v1.AgentService/ReadMemory"
	AgentService_RenderSystemPrompt_FullMethodName       = "/wackypub.agent.v1.AgentService/RenderSystemPrompt"
	AgentService_InspectSessionContext_FullMethodName    = "/wackypub.agent.v1.AgentService/InspectSessionContext"
	AgentService_InspectAgentLocks_FullMethodName        = "/wackypub.agent.v1.AgentService/InspectAgentLocks"
	AgentService_AddUserTurn_FullMethodName              = "/wackypub.agent.v1.AgentService/AddUserTurn"
	AgentService_AddMedia_FullMethodName                 = "/wackypub.agent.v1.AgentService/AddMedia"
	AgentService_CancelTurn_FullMethodName               = "/wackypub.agent.v1.AgentService/CancelTurn"
	AgentService_StripSignatures_FullMethodName          = "/wackypub.agent.v1.AgentService/StripSignatures"
	AgentService_CompactSession_FullMethodName           = "/wackypub.agent.v1.AgentService/CompactSession"
	AgentService_CreateScratchpad_FullMethodName         = "/wackypub.agent.v1.AgentService/CreateScratchpad"
	AgentService_GetScratchpad_FullMethodName            = "/wackypub.agent.v1.AgentService/GetScratchpad"
	AgentService_ListScratchpads_FullMethodName          = "/wackypub.agent.v1.AgentService/ListScratchpads"
	AgentService_SearchScratchpad_FullMethodName         = "/wackypub.agent.v1.AgentService/SearchScratchpad"
	AgentService_DiffScratchpadEntries_FullMethodName    = "/wackypub.agent.v1.AgentService/DiffScratchpadEntries"
	AgentService_DeleteScratchpad_FullMethodName         = "/wackypub.agent.v1.AgentService/DeleteScratchpad"
	AgentService_GenerateTurnStream_FullMethodName       = "/wackypub.agent.v1.AgentService/GenerateTurnStream"
	AgentService_GenerateTurn_FullMethodName             = "/wackypub.agent.v1.AgentService/GenerateTurn"
	AgentService_AddAndGenerateTurnStream_FullMethodName = "/wackypub.agent.v1.AgentService/AddAndGenerateTurnStream"
	AgentService_AddAndGenerateTurn_FullMethodName       = "/wackypub.agent.v1.AgentService/AddAndGenerateTurn"
	AgentService_Trace_FullMethodName                    = "/wackypub.agent.v1.AgentService/Trace"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService defines the interface of record for WackyPub agent operations (D112).
//
// In v1, this interface is consumed strictly in-process through generated Go types
// and interfaces; no network transport (gRPC/HTTP), network listener, or remote daemon
// is deployed or required. The protobuf definition serves as the canonical contract
// defining operation semantics, data models, and migration boundaries for the WackyPub
// agent lifecycle.
//
// D112 establishes a unified 26-method service interface replacing the legacy monolithic
// AgentSDK methods across five staged rollout phases:
//   - Phase 1: Read-only workspace queries and state inspection (7 methods:
//     ListAgents, InspectAgent, ReadSession, ReadMemory, RenderSystemPrompt,
//     InspectSessionContext, InspectAgentLocks).
//   - Phase 3: Stateful mutations (AddUserTurn, AddMedia, CancelTurn, StripSignatures,
//     CompactSession) and scratchpad CRUD (CreateScratchpad, GetScratchpad, ListScratchpads,
//     SearchScratchpad, DiffScratchpadEntries, DeleteScratchpad).
//   - Phase 4 (current): Side-effectful / background operations (Trace).
//   - Phase 5: Complete cutover and deprecation/removal of legacy SDK entry points.
//
// Design Decisions:
//   - Q1: Go code generation produces interface stubs (AgentServiceServer) embedded directly
//     into AgentSDK without network overhead.
//   - Q2: Protobuf service definitions are the sole source of truth for method signatures
//     and wire structures, replacing ad-hoc Go structs.
//   - Q5: Staged migration permits progressive implementation and contract testing while
//     keeping existing CLI workflows fully backward-compatible.
type AgentServiceClient interface {
	// ListAgents discovers and returns the identifiers of all agent directories present
	// directly under the specified workspace root. An agent directory is recognized if it
	// contains the marker file (AGENTS.md). Callers invoke this method during workspace
	// discovery, multi-agent orchestration, or status reporting. If the workspace directory
	// does not exist or contains no valid agent directories, an empty list is returned without error.
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// InspectAgent performs an extensive diagnostic audit of an agent directory's filesystem state.
	// Callers invoke this method to determine configuration completeness, file presence, allowlists,
	// discovered tools and skills, and session corruption statistics without triggering agent execution
	// or modifying on-disk state. This call intentionally avoids acquiring session locks to prevent
	// self-deadlocks when called by an agent inspecting itself mid-turn. If the target agent directory
	// does not exist, the response sets agent_dir_exists to false with all remaining fields zero-valued.
	InspectAgent(ctx context.Context, in *InspectAgentRequest, opts ...grpc.CallOption) (*InspectAgentResponse, error)
	// ReadSession reads and returns the full conversational turn history stored in the agent's
	// session.jsonl file. Callers use this method to inspect past user/model interactions, replay
	// conversations, or audit transcripts. In v1, turns and content parts are converted to SessionTurn
	// structures containing plain text and inline data; tool invocations (FunctionCall and FunctionResponse)
	// are omitted under accepted-lossy v1 conversion. If session.jsonl does not exist, an empty list
	// of turns is returned without error.
	ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...grpc.CallOption) (*ReadSessionResponse, error)
	// ReadMemory retrieves the raw markdown content of the agent's long-term memory notes from
	// MEMORY.md. Callers use this method to read persistent memories across sessions. Read access
	// is subject to workspace allowlist authorization against the target agent. If MEMORY.md does
	// not exist, an empty string is returned without error.
	ReadMemory(ctx context.Context, in *ReadMemoryRequest, opts ...grpc.CallOption) (*ReadMemoryResponse, error)
	// RenderSystemPrompt renders the agent's complete system prompt from AGENTS.md, expanding
	// any macro inclusion directives (@<FILE_PATH>) into their referenced file contents. Callers
	// use this method to view or feed the actual prompt passed to the model backend during generation.
	// Returns an error if AGENTS.md cannot be read or if cyclic macro references are detected.
	RenderSystemPrompt(ctx context.Context, in *RenderSystemPromptRequest, opts ...grpc.CallOption) (*RenderSystemPromptResponse, error)
	// InspectSessionContext calculates current token usage, context window limits, and auto-compaction
	// headroom for an agent per D93/D101. Callers invoke this method to monitor context window consumption,
	// plan proactive compaction, or display diagnostics. It estimates token counts across session turns,
	// the rendered system prompt, and memory files, returning headroom percentages and the most recent turn
	// token metrics if available.
	InspectSessionContext(ctx context.Context, in *InspectSessionContextRequest, opts ...grpc.CallOption) (*InspectSessionContextResponse, error)
	// InspectAgentLocks surveys all agent directories in the workspace and returns lock status and session
	// activity for each agent per D100. Callers invoke this method to detect active agent executions, identify
	// stale lock files left behind by dead processes, or debug concurrency contention. The lock file outlives
	// release, so lock presence alone does not imply held; callers must check holder_pid_valid, holder_alive,
	// and last_write.
	InspectAgentLocks(ctx context.Context, in *InspectAgentLocksRequest, opts ...grpc.CallOption) (*InspectAgentLocksResponse, error)
	// AddUserTurn appends a new user message turn to the agent's conversational session history (session.jsonl).
	// Automatically creates the agent directory if it does not yet exist. Executes configured user message
	// lifecycle hooks before committing the turn, returning any non-fatal hook warnings alongside the committed turn.
	// Acquires the agent's exclusive session lock for the duration of the append.
	AddUserTurn(ctx context.Context, in *AddUserTurnRequest, opts ...grpc.CallOption) (*AddUserTurnResponse, error)
	// AddMedia attaches a binary image payload to the agent's conversational session history (session.jsonl).
	// The image bytes are validated, normalized, and resized to JPEG format according to maxImageDimension
	// in runtime.json per D47. Payloads exceeding the 10MB ceiling (MaxMediaPayloadBytes) are rejected outright.
	// Acquires the agent's exclusive session lock for the duration of the operation.
	AddMedia(ctx context.Context, in *AddMediaRequest, opts ...grpc.CallOption) (*AddMediaResponse, error)
	// CancelTurn cancels an active in-flight turn for the specified agent (D85).
	// Safe to invoke concurrently from any goroutine. Returns an error if no turn is currently
	// active for the specified agent.
	CancelTurn(ctx context.Context, in *CancelTurnRequest, opts ...grpc.CallOption) (*CancelTurnResponse, error)
	// StripSignatures strips provider-specific opaque reasoning/thought signatures (such as Gemini's
	// ThoughtSignature or OpenRouter reasoning_details) from all turns in session.jsonl, rewriting the file
	// in place. Readable plain-text reasoning is preserved. Useful when switching an agent between LLM
	// providers where replaying previous provider signatures causes rejection. Acquires the session lock.
	StripSignatures(ctx context.Context, in *StripSignaturesRequest, opts ...grpc.CallOption) (*StripSignaturesResponse, error)
	// CompactSession evaluates and triggers session compaction on an agent's history (D44, D83, D84).
	// Summarizes the oldest turns (default 50%, or compact_pct in COMPACT.md) into MEMORY.md and removes
	// them from session.jsonl. Callers can force compaction (bypassing token headroom thresholds), provide
	// an in-memory CompactConfig override, or specify an alternative runtime configuration path.
	// Acquires the exclusive session lock for the duration of compaction.
	CompactSession(ctx context.Context, in *CompactSessionRequest, opts ...grpc.CallOption) (*CompactSessionResponse, error)
	// CreateScratchpad writes a new entry to the agent's scratchpad store (<workspace_dir>/<agent_id>/scratchpad/).
	// Performs atomic creation and enforces store capacity limits (MaxScratchpadEntries). Does not require the
	// session lock.
	CreateScratchpad(ctx context.Context, in *CreateScratchpadRequest, opts ...grpc.CallOption) (*CreateScratchpadResponse, error)
	// GetScratchpad retrieves the text content of a specific scratchpad entry from the agent's scratchpad store.
	// Supports optional pagination via skip_lines and num_lines. Does not require the session lock.
	GetScratchpad(ctx context.Context, in *GetScratchpadRequest, opts ...grpc.CallOption) (*GetScratchpadResponse, error)
	// ListScratchpads lists metadata for all scratchpad entries present in the agent's scratchpad store.
	// Returns entries ordered chronologically along with current capacity metrics. Does not require the session lock.
	ListScratchpads(ctx context.Context, in *ListScratchpadsRequest, opts ...grpc.CallOption) (*ListScratchpadsResponse, error)
	// SearchScratchpad searches the text of a specific scratchpad entry for matching lines.
	// Supports case-sensitivity toggles, regular expressions, and result limits. Rejects binary entries.
	// Does not require the session lock.
	SearchScratchpad(ctx context.Context, in *SearchScratchpadRequest, opts ...grpc.CallOption) (*SearchScratchpadResponse, error)
	// DiffScratchpadEntries computes and returns a unified diff between two scratchpad entries for an agent.
	// Returns an empty diff string if both entries are byte-identical. Does not require the session lock.
	DiffScratchpadEntries(ctx context.Context, in *DiffScratchpadEntriesRequest, opts ...grpc.CallOption) (*DiffScratchpadEntriesResponse, error)
	// DeleteScratchpad removes a scratchpad entry from the agent's scratchpad store by its identifier.
	// Enforces workspace allowlist authorization.
	DeleteScratchpad(ctx context.Context, in *DeleteScratchpadRequest, opts ...grpc.CallOption) (*DeleteScratchpadResponse, error)
	// GenerateTurnStream generates the next assistant turn for an agent whose session
	// already contains pending history, streaming text chunks to the caller as the model
	// produces them. The request carries no user message - the turn continues from whatever
	// is already in session.jsonl (e.g. a turn queued by AddUserTurn). It holds the session
	// lock for the entire stream, and the stream is cancelled when the caller stops iterating
	// or the context expires.
	GenerateTurnStream(ctx context.Context, in *GenerateTurnStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateTurnStreamResponse], error)
	// GenerateTurn is the non-streaming twin of GenerateTurnStream: it runs the same
	// generation path and returns the complete assistant text joined across chunks.
	GenerateTurn(ctx context.Context, in *GenerateTurnRequest, opts ...grpc.CallOption) (*GenerateTurnResponse, error)
	// AddAndGenerateTurnStream atomically appends a user message to the agent session and
	// streams the assistant response chunks as they are generated, under a single session
	// lock. Hook execution warnings are carried on the chunk stream itself (a chunk with
	// warning set and empty text) so in-process consumers do not need a Go-only callback.
	AddAndGenerateTurnStream(ctx context.Context, in *AddAndGenerateTurnStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AddAndGenerateTurnStreamResponse], error)
	// AddAndGenerateTurn is the non-streaming twin of AddAndGenerateTurnStream: it appends
	// the user message, runs the full generation, and returns the complete assistant text
	// plus any hook warnings on the response.
	AddAndGenerateTurn(ctx context.Context, in *AddAndGenerateTurnRequest, opts ...grpc.CallOption) (*AddAndGenerateTurnResponse, error)
	// Trace performs backward causal graph traversal starting from an agent's git commit or a global
	// correlation trace identifier (D36). Callers invoke this method to audit cross-agent workflows,
	// inspect multi-hop turn histories, and reconstruct causal chains. The request uses a oneof to enforce
	// that callers specify either an agent commit specifier or a trace ID.
	Trace(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InspectAgent(ctx context.Context, in *InspectAgentRequest, opts ...grpc.CallOption) (*InspectAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_InspectAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...grpc.CallOption) (*ReadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_ReadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReadMemory(ctx context.Context, in *ReadMemoryRequest, opts ...grpc.CallOption) (*ReadMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadMemoryResponse)
	err := c.cc.Invoke(ctx, AgentService_ReadMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RenderSystemPrompt(ctx context.Context, in *RenderSystemPromptRequest, opts ...grpc.CallOption) (*RenderSystemPromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderSystemPromptResponse)
	err := c.cc.Invoke(ctx, AgentService_RenderSystemPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InspectSessionContext(ctx context.Context, in *InspectSessionContextRequest, opts ...grpc.CallOption) (*InspectSessionContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectSessionContextResponse)
	err := c.cc.Invoke(ctx, AgentService_InspectSessionContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InspectAgentLocks(ctx context.Context, in *InspectAgentLocksRequest, opts ...grpc.CallOption) (*InspectAgentLocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectAgentLocksResponse)
	err := c.cc.Invoke(ctx, AgentService_InspectAgentLocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AddUserTurn(ctx context.Context, in *AddUserTurnRequest, opts ...grpc.CallOption) (*AddUserTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserTurnResponse)
	err := c.cc.Invoke(ctx, AgentService_AddUserTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AddMedia(ctx context.Context, in *AddMediaRequest, opts ...grpc.CallOption) (*AddMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMediaResponse)
	err := c.cc.Invoke(ctx, AgentService_AddMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CancelTurn(ctx context.Context, in *CancelTurnRequest, opts ...grpc.CallOption) (*CancelTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTurnResponse)
	err := c.cc.Invoke(ctx, AgentService_CancelTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StripSignatures(ctx context.Context, in *StripSignaturesRequest, opts ...grpc.CallOption) (*StripSignaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StripSignaturesResponse)
	err := c.cc.Invoke(ctx, AgentService_StripSignatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CompactSession(ctx context.Context, in *CompactSessionRequest, opts ...grpc.CallOption) (*CompactSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_CompactSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateScratchpad(ctx context.Context, in *CreateScratchpadRequest, opts ...grpc.CallOption) (*CreateScratchpadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScratchpadResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateScratchpad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetScratchpad(ctx context.Context, in *GetScratchpadRequest, opts ...grpc.CallOption) (*GetScratchpadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScratchpadResponse)
	err := c.cc.Invoke(ctx, AgentService_GetScratchpad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListScratchpads(ctx context.Context, in *ListScratchpadsRequest, opts ...grpc.CallOption) (*ListScratchpadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScratchpadsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListScratchpads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SearchScratchpad(ctx context.Context, in *SearchScratchpadRequest, opts ...grpc.CallOption) (*SearchScratchpadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchScratchpadResponse)
	err := c.cc.Invoke(ctx, AgentService_SearchScratchpad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DiffScratchpadEntries(ctx context.Context, in *DiffScratchpadEntriesRequest, opts ...grpc.CallOption) (*DiffScratchpadEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffScratchpadEntriesResponse)
	err := c.cc.Invoke(ctx, AgentService_DiffScratchpadEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteScratchpad(ctx context.Context, in *DeleteScratchpadRequest, opts ...grpc.CallOption) (*DeleteScratchpadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScratchpadResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteScratchpad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GenerateTurnStream(ctx context.Context, in *GenerateTurnStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateTurnStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_GenerateTurnStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateTurnStreamRequest, GenerateTurnStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GenerateTurnStreamClient = grpc.ServerStreamingClient[GenerateTurnStreamResponse]

func (c *agentServiceClient) GenerateTurn(ctx context.Context, in *GenerateTurnRequest, opts ...grpc.CallOption) (*GenerateTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTurnResponse)
	err := c.cc.Invoke(ctx, AgentService_GenerateTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AddAndGenerateTurnStream(ctx context.Context, in *AddAndGenerateTurnStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AddAndGenerateTurnStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_AddAndGenerateTurnStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddAndGenerateTurnStreamRequest, AddAndGenerateTurnStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_AddAndGenerateTurnStreamClient = grpc.ServerStreamingClient[AddAndGenerateTurnStreamResponse]

func (c *agentServiceClient) AddAndGenerateTurn(ctx context.Context, in *AddAndGenerateTurnRequest, opts ...grpc.CallOption) (*AddAndGenerateTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAndGenerateTurnResponse)
	err := c.cc.Invoke(ctx, AgentService_AddAndGenerateTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Trace(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceResponse)
	err := c.cc.Invoke(ctx, AgentService_Trace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations should embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService defines the interface of record for WackyPub agent operations (D112).
//
// In v1, this interface is consumed strictly in-process through generated Go types
// and interfaces; no network transport (gRPC/HTTP), network listener, or remote daemon
// is deployed or required. The protobuf definition serves as the canonical contract
// defining operation semantics, data models, and migration boundaries for the WackyPub
// agent lifecycle.
//
// D112 establishes a unified 26-method service interface replacing the legacy monolithic
// AgentSDK methods across five staged rollout phases:
//   - Phase 1: Read-only workspace queries and state inspection (7 methods:
//     ListAgents, InspectAgent, ReadSession, ReadMemory, RenderSystemPrompt,
//     InspectSessionContext, InspectAgentLocks).
//   - Phase 3: Stateful mutations (AddUserTurn, AddMedia, CancelTurn, StripSignatures,
//     CompactSession) and scratchpad CRUD (CreateScratchpad, GetScratchpad, ListScratchpads,
//     SearchScratchpad, DiffScratchpadEntries, DeleteScratchpad).
//   - Phase 4 (current): Side-effectful / background operations (Trace).
//   - Phase 5: Complete cutover and deprecation/removal of legacy SDK entry points.
//
// Design Decisions:
//   - Q1: Go code generation produces interface stubs (AgentServiceServer) embedded directly
//     into AgentSDK without network overhead.
//   - Q2: Protobuf service definitions are the sole source of truth for method signatures
//     and wire structures, replacing ad-hoc Go structs.
//   - Q5: Staged migration permits progressive implementation and contract testing while
//     keeping existing CLI workflows fully backward-compatible.
type AgentServiceServer interface {
	// ListAgents discovers and returns the identifiers of all agent directories present
	// directly under the specified workspace root. An agent directory is recognized if it
	// contains the marker file (AGENTS.md). Callers invoke this method during workspace
	// discovery, multi-agent orchestration, or status reporting. If the workspace directory
	// does not exist or contains no valid agent directories, an empty list is returned without error.
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// InspectAgent performs an extensive diagnostic audit of an agent directory's filesystem state.
	// Callers invoke this method to determine configuration completeness, file presence, allowlists,
	// discovered tools and skills, and session corruption statistics without triggering agent execution
	// or modifying on-disk state. This call intentionally avoids acquiring session locks to prevent
	// self-deadlocks when called by an agent inspecting itself mid-turn. If the target agent directory
	// does not exist, the response sets agent_dir_exists to false with all remaining fields zero-valued.
	InspectAgent(context.Context, *InspectAgentRequest) (*InspectAgentResponse, error)
	// ReadSession reads and returns the full conversational turn history stored in the agent's
	// session.jsonl file. Callers use this method to inspect past user/model interactions, replay
	// conversations, or audit transcripts. In v1, turns and content parts are converted to SessionTurn
	// structures containing plain text and inline data; tool invocations (FunctionCall and FunctionResponse)
	// are omitted under accepted-lossy v1 conversion. If session.jsonl does not exist, an empty list
	// of turns is returned without error.
	ReadSession(context.Context, *ReadSessionRequest) (*ReadSessionResponse, error)
	// ReadMemory retrieves the raw markdown content of the agent's long-term memory notes from
	// MEMORY.md. Callers use this method to read persistent memories across sessions. Read access
	// is subject to workspace allowlist authorization against the target agent. If MEMORY.md does
	// not exist, an empty string is returned without error.
	ReadMemory(context.Context, *ReadMemoryRequest) (*ReadMemoryResponse, error)
	// RenderSystemPrompt renders the agent's complete system prompt from AGENTS.md, expanding
	// any macro inclusion directives (@<FILE_PATH>) into their referenced file contents. Callers
	// use this method to view or feed the actual prompt passed to the model backend during generation.
	// Returns an error if AGENTS.md cannot be read or if cyclic macro references are detected.
	RenderSystemPrompt(context.Context, *RenderSystemPromptRequest) (*RenderSystemPromptResponse, error)
	// InspectSessionContext calculates current token usage, context window limits, and auto-compaction
	// headroom for an agent per D93/D101. Callers invoke this method to monitor context window consumption,
	// plan proactive compaction, or display diagnostics. It estimates token counts across session turns,
	// the rendered system prompt, and memory files, returning headroom percentages and the most recent turn
	// token metrics if available.
	InspectSessionContext(context.Context, *InspectSessionContextRequest) (*InspectSessionContextResponse, error)
	// InspectAgentLocks surveys all agent directories in the workspace and returns lock status and session
	// activity for each agent per D100. Callers invoke this method to detect active agent executions, identify
	// stale lock files left behind by dead processes, or debug concurrency contention. The lock file outlives
	// release, so lock presence alone does not imply held; callers must check holder_pid_valid, holder_alive,
	// and last_write.
	InspectAgentLocks(context.Context, *InspectAgentLocksRequest) (*InspectAgentLocksResponse, error)
	// AddUserTurn appends a new user message turn to the agent's conversational session history (session.jsonl).
	// Automatically creates the agent directory if it does not yet exist. Executes configured user message
	// lifecycle hooks before committing the turn, returning any non-fatal hook warnings alongside the committed turn.
	// Acquires the agent's exclusive session lock for the duration of the append.
	AddUserTurn(context.Context, *AddUserTurnRequest) (*AddUserTurnResponse, error)
	// AddMedia attaches a binary image payload to the agent's conversational session history (session.jsonl).
	// The image bytes are validated, normalized, and resized to JPEG format according to maxImageDimension
	// in runtime.json per D47. Payloads exceeding the 10MB ceiling (MaxMediaPayloadBytes) are rejected outright.
	// Acquires the agent's exclusive session lock for the duration of the operation.
	AddMedia(context.Context, *AddMediaRequest) (*AddMediaResponse, error)
	// CancelTurn cancels an active in-flight turn for the specified agent (D85).
	// Safe to invoke concurrently from any goroutine. Returns an error if no turn is currently
	// active for the specified agent.
	CancelTurn(context.Context, *CancelTurnRequest) (*CancelTurnResponse, error)
	// StripSignatures strips provider-specific opaque reasoning/thought signatures (such as Gemini's
	// ThoughtSignature or OpenRouter reasoning_details) from all turns in session.jsonl, rewriting the file
	// in place. Readable plain-text reasoning is preserved. Useful when switching an agent between LLM
	// providers where replaying previous provider signatures causes rejection. Acquires the session lock.
	StripSignatures(context.Context, *StripSignaturesRequest) (*StripSignaturesResponse, error)
	// CompactSession evaluates and triggers session compaction on an agent's history (D44, D83, D84).
	// Summarizes the oldest turns (default 50%, or compact_pct in COMPACT.md) into MEMORY.md and removes
	// them from session.jsonl. Callers can force compaction (bypassing token headroom thresholds), provide
	// an in-memory CompactConfig override, or specify an alternative runtime configuration path.
	// Acquires the exclusive session lock for the duration of compaction.
	CompactSession(context.Context, *CompactSessionRequest) (*CompactSessionResponse, error)
	// CreateScratchpad writes a new entry to the agent's scratchpad store (<workspace_dir>/<agent_id>/scratchpad/).
	// Performs atomic creation and enforces store capacity limits (MaxScratchpadEntries). Does not require the
	// session lock.
	CreateScratchpad(context.Context, *CreateScratchpadRequest) (*CreateScratchpadResponse, error)
	// GetScratchpad retrieves the text content of a specific scratchpad entry from the agent's scratchpad store.
	// Supports optional pagination via skip_lines and num_lines. Does not require the session lock.
	GetScratchpad(context.Context, *GetScratchpadRequest) (*GetScratchpadResponse, error)
	// ListScratchpads lists metadata for all scratchpad entries present in the agent's scratchpad store.
	// Returns entries ordered chronologically along with current capacity metrics. Does not require the session lock.
	ListScratchpads(context.Context, *ListScratchpadsRequest) (*ListScratchpadsResponse, error)
	// SearchScratchpad searches the text of a specific scratchpad entry for matching lines.
	// Supports case-sensitivity toggles, regular expressions, and result limits. Rejects binary entries.
	// Does not require the session lock.
	SearchScratchpad(context.Context, *SearchScratchpadRequest) (*SearchScratchpadResponse, error)
	// DiffScratchpadEntries computes and returns a unified diff between two scratchpad entries for an agent.
	// Returns an empty diff string if both entries are byte-identical. Does not require the session lock.
	DiffScratchpadEntries(context.Context, *DiffScratchpadEntriesRequest) (*DiffScratchpadEntriesResponse, error)
	// DeleteScratchpad removes a scratchpad entry from the agent's scratchpad store by its identifier.
	// Enforces workspace allowlist authorization.
	DeleteScratchpad(context.Context, *DeleteScratchpadRequest) (*DeleteScratchpadResponse, error)
	// GenerateTurnStream generates the next assistant turn for an agent whose session
	// already contains pending history, streaming text chunks to the caller as the model
	// produces them. The request carries no user message - the turn continues from whatever
	// is already in session.jsonl (e.g. a turn queued by AddUserTurn). It holds the session
	// lock for the entire stream, and the stream is cancelled when the caller stops iterating
	// or the context expires.
	GenerateTurnStream(*GenerateTurnStreamRequest, grpc.ServerStreamingServer[GenerateTurnStreamResponse]) error
	// GenerateTurn is the non-streaming twin of GenerateTurnStream: it runs the same
	// generation path and returns the complete assistant text joined across chunks.
	GenerateTurn(context.Context, *GenerateTurnRequest) (*GenerateTurnResponse, error)
	// AddAndGenerateTurnStream atomically appends a user message to the agent session and
	// streams the assistant response chunks as they are generated, under a single session
	// lock. Hook execution warnings are carried on the chunk stream itself (a chunk with
	// warning set and empty text) so in-process consumers do not need a Go-only callback.
	AddAndGenerateTurnStream(*AddAndGenerateTurnStreamRequest, grpc.ServerStreamingServer[AddAndGenerateTurnStreamResponse]) error
	// AddAndGenerateTurn is the non-streaming twin of AddAndGenerateTurnStream: it appends
	// the user message, runs the full generation, and returns the complete assistant text
	// plus any hook warnings on the response.
	AddAndGenerateTurn(context.Context, *AddAndGenerateTurnRequest) (*AddAndGenerateTurnResponse, error)
	// Trace performs backward causal graph traversal starting from an agent's git commit or a global
	// correlation trace identifier (D36). Callers invoke this method to audit cross-agent workflows,
	// inspect multi-hop turn histories, and reconstruct causal chains. The request uses a oneof to enforce
	// that callers specify either an agent commit specifier or a trace ID.
	Trace(context.Context, *TraceRequest) (*TraceResponse, error)
}

// UnimplementedAgentServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentServiceServer) InspectAgent(context.Context, *InspectAgentRequest) (*InspectAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectAgent not implemented")
}
func (UnimplementedAgentServiceServer) ReadSession(context.Context, *ReadSessionRequest) (*ReadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadSession not implemented")
}
func (UnimplementedAgentServiceServer) ReadMemory(context.Context, *ReadMemoryRequest) (*ReadMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadMemory not implemented")
}
func (UnimplementedAgentServiceServer) RenderSystemPrompt(context.Context, *RenderSystemPromptRequest) (*RenderSystemPromptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderSystemPrompt not implemented")
}
func (UnimplementedAgentServiceServer) InspectSessionContext(context.Context, *InspectSessionContextRequest) (*InspectSessionContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectSessionContext not implemented")
}
func (UnimplementedAgentServiceServer) InspectAgentLocks(context.Context, *InspectAgentLocksRequest) (*InspectAgentLocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectAgentLocks not implemented")
}
func (UnimplementedAgentServiceServer) AddUserTurn(context.Context, *AddUserTurnRequest) (*AddUserTurnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserTurn not implemented")
}
func (UnimplementedAgentServiceServer) AddMedia(context.Context, *AddMediaRequest) (*AddMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMedia not implemented")
}
func (UnimplementedAgentServiceServer) CancelTurn(context.Context, *CancelTurnRequest) (*CancelTurnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTurn not implemented")
}
func (UnimplementedAgentServiceServer) StripSignatures(context.Context, *StripSignaturesRequest) (*StripSignaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StripSignatures not implemented")
}
func (UnimplementedAgentServiceServer) CompactSession(context.Context, *CompactSessionRequest) (*CompactSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompactSession not implemented")
}
func (UnimplementedAgentServiceServer) CreateScratchpad(context.Context, *CreateScratchpadRequest) (*CreateScratchpadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScratchpad not implemented")
}
func (UnimplementedAgentServiceServer) GetScratchpad(context.Context, *GetScratchpadRequest) (*GetScratchpadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScratchpad not implemented")
}
func (UnimplementedAgentServiceServer) ListScratchpads(context.Context, *ListScratchpadsRequest) (*ListScratchpadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScratchpads not implemented")
}
func (UnimplementedAgentServiceServer) SearchScratchpad(context.Context, *SearchScratchpadRequest) (*SearchScratchpadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchScratchpad not implemented")
}
func (UnimplementedAgentServiceServer) DiffScratchpadEntries(context.Context, *DiffScratchpadEntriesRequest) (*DiffScratchpadEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffScratchpadEntries not implemented")
}
func (UnimplementedAgentServiceServer) DeleteScratchpad(context.Context, *DeleteScratchpadRequest) (*DeleteScratchpadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteScratchpad not implemented")
}
func (UnimplementedAgentServiceServer) GenerateTurnStream(*GenerateTurnStreamRequest, grpc.ServerStreamingServer[GenerateTurnStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateTurnStream not implemented")
}
func (UnimplementedAgentServiceServer) GenerateTurn(context.Context, *GenerateTurnRequest) (*GenerateTurnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateTurn not implemented")
}
func (UnimplementedAgentServiceServer) AddAndGenerateTurnStream(*AddAndGenerateTurnStreamRequest, grpc.ServerStreamingServer[AddAndGenerateTurnStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method AddAndGenerateTurnStream not implemented")
}
func (UnimplementedAgentServiceServer) AddAndGenerateTurn(context.Context, *AddAndGenerateTurnRequest) (*AddAndGenerateTurnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAndGenerateTurn not implemented")
}
func (UnimplementedAgentServiceServer) Trace(context.Context, *TraceRequest) (*TraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Trace not implemented")
}
func (UnimplementedAgentServiceServer) testEmbeddedByValue() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InspectAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InspectAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InspectAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InspectAgent(ctx, req.(*InspectAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReadSession(ctx, req.(*ReadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReadMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReadMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReadMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReadMemory(ctx, req.(*ReadMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RenderSystemPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderSystemPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RenderSystemPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RenderSystemPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RenderSystemPrompt(ctx, req.(*RenderSystemPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InspectSessionContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectSessionContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InspectSessionContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InspectSessionContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InspectSessionContext(ctx, req.(*InspectSessionContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InspectAgentLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectAgentLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InspectAgentLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InspectAgentLocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InspectAgentLocks(ctx, req.(*InspectAgentLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AddUserTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AddUserTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AddUserTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AddUserTurn(ctx, req.(*AddUserTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AddMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AddMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AddMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AddMedia(ctx, req.(*AddMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CancelTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CancelTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CancelTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CancelTurn(ctx, req.(*CancelTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StripSignatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StripSignaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StripSignatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StripSignatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StripSignatures(ctx, req.(*StripSignaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CompactSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CompactSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CompactSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CompactSession(ctx, req.(*CompactSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateScratchpad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScratchpadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateScratchpad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateScratchpad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateScratchpad(ctx, req.(*CreateScratchpadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetScratchpad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScratchpadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetScratchpad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetScratchpad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetScratchpad(ctx, req.(*GetScratchpadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListScratchpads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScratchpadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListScratchpads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListScratchpads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListScratchpads(ctx, req.(*ListScratchpadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SearchScratchpad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchScratchpadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SearchScratchpad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SearchScratchpad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SearchScratchpad(ctx, req.(*SearchScratchpadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DiffScratchpadEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffScratchpadEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DiffScratchpadEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DiffScratchpadEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DiffScratchpadEntries(ctx, req.(*DiffScratchpadEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteScratchpad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScratchpadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteScratchpad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteScratchpad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteScratchpad(ctx, req.(*DeleteScratchpadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GenerateTurnStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateTurnStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).GenerateTurnStream(m, &grpc.GenericServerStream[GenerateTurnStreamRequest, GenerateTurnStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GenerateTurnStreamServer = grpc.ServerStreamingServer[GenerateTurnStreamResponse]

func _AgentService_GenerateTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GenerateTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GenerateTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GenerateTurn(ctx, req.(*GenerateTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AddAndGenerateTurnStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddAndGenerateTurnStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).AddAndGenerateTurnStream(m, &grpc.GenericServerStream[AddAndGenerateTurnStreamRequest, AddAndGenerateTurnStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_AddAndGenerateTurnStreamServer = grpc.ServerStreamingServer[AddAndGenerateTurnStreamResponse]

func _AgentService_AddAndGenerateTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAndGenerateTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AddAndGenerateTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AddAndGenerateTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AddAndGenerateTurn(ctx, req.(*AddAndGenerateTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Trace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Trace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Trace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Trace(ctx, req.(*TraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wackypub.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgents",
			Handler:    _AgentService_ListAgents_Handler,
		},
		{
			MethodName: "InspectAgent",
			Handler:    _AgentService_InspectAgent_Handler,
		},
		{
			MethodName: "ReadSession",
			Handler:    _AgentService_ReadSession_Handler,
		},
		{
			MethodName: "ReadMemory",
			Handler:    _AgentService_ReadMemory_Handler,
		},
		{
			MethodName: "RenderSystemPrompt",
			Handler:    _AgentService_RenderSystemPrompt_Handler,
		},
		{
			MethodName: "InspectSessionContext",
			Handler:    _AgentService_InspectSessionContext_Handler,
		},
		{
			MethodName: "InspectAgentLocks",
			Handler:    _AgentService_InspectAgentLocks_Handler,
		},
		{
			MethodName: "AddUserTurn",
			Handler:    _AgentService_AddUserTurn_Handler,
		},
		{
			MethodName: "AddMedia",
			Handler:    _AgentService_AddMedia_Handler,
		},
		{
			MethodName: "CancelTurn",
			Handler:    _AgentService_CancelTurn_Handler,
		},
		{
			MethodName: "StripSignatures",
			Handler:    _AgentService_StripSignatures_Handler,
		},
		{
			MethodName: "CompactSession",
			Handler:    _AgentService_CompactSession_Handler,
		},
		{
			MethodName: "CreateScratchpad",
			Handler:    _AgentService_CreateScratchpad_Handler,
		},
		{
			MethodName: "GetScratchpad",
			Handler:    _AgentService_GetScratchpad_Handler,
		},
		{
			MethodName: "ListScratchpads",
			Handler:    _AgentService_ListScratchpads_Handler,
		},
		{
			MethodName: "SearchScratchpad",
			Handler:    _AgentService_SearchScratchpad_Handler,
		},
		{
			MethodName: "DiffScratchpadEntries",
			Handler:    _AgentService_DiffScratchpadEntries_Handler,
		},
		{
			MethodName: "DeleteScratchpad",
			Handler:    _AgentService_DeleteScratchpad_Handler,
		},
		{
			MethodName: "GenerateTurn",
			Handler:    _AgentService_GenerateTurn_Handler,
		},
		{
			MethodName: "AddAndGenerateTurn",
			Handler:    _AgentService_AddAndGenerateTurn_Handler,
		},
		{
			MethodName: "Trace",
			Handler:    _AgentService_Trace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateTurnStream",
			Handler:       _AgentService_GenerateTurnStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddAndGenerateTurnStream",
			Handler:       _AgentService_AddAndGenerateTurnStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
