// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListAgentsRequest specifies parameters for listing agents.
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceDir  string                 `protobuf:"bytes,1,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ListAgentsRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

// ListAgentsResponse contains the IDs of all discovered agents.
type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentIds      []string               `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsResponse) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

// InspectAgentRequest specifies parameters for inspecting an agent.
type InspectAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorkspaceDir  string                 `protobuf:"bytes,2,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectAgentRequest) Reset() {
	*x = InspectAgentRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectAgentRequest) ProtoMessage() {}

func (x *InspectAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectAgentRequest.ProtoReflect.Descriptor instead.
func (*InspectAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *InspectAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InspectAgentRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

// InspectAgentResponse contains the inspection details of an agent directory.
type InspectAgentResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AgentId              string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentDir             string                 `protobuf:"bytes,2,opt,name=agent_dir,json=agentDir,proto3" json:"agent_dir,omitempty"`
	AgentDirExists       bool                   `protobuf:"varint,3,opt,name=agent_dir_exists,json=agentDirExists,proto3" json:"agent_dir_exists,omitempty"`
	AgentsMdExists       bool                   `protobuf:"varint,4,opt,name=agents_md_exists,json=agentsMdExists,proto3" json:"agents_md_exists,omitempty"`
	MemoryMdExists       bool                   `protobuf:"varint,5,opt,name=memory_md_exists,json=memoryMdExists,proto3" json:"memory_md_exists,omitempty"`
	DotEnvExists         bool                   `protobuf:"varint,6,opt,name=dot_env_exists,json=dotEnvExists,proto3" json:"dot_env_exists,omitempty"`
	RuntimeJsonExists    bool                   `protobuf:"varint,7,opt,name=runtime_json_exists,json=runtimeJsonExists,proto3" json:"runtime_json_exists,omitempty"`
	RuntimeJsonIsSymlink bool                   `protobuf:"varint,8,opt,name=runtime_json_is_symlink,json=runtimeJsonIsSymlink,proto3" json:"runtime_json_is_symlink,omitempty"`
	RuntimeJsonResolved  string                 `protobuf:"bytes,9,opt,name=runtime_json_resolved,json=runtimeJsonResolved,proto3" json:"runtime_json_resolved,omitempty"`
	RuntimeJsonValid     bool                   `protobuf:"varint,10,opt,name=runtime_json_valid,json=runtimeJsonValid,proto3" json:"runtime_json_valid,omitempty"`
	RuntimeJsonError     string                 `protobuf:"bytes,11,opt,name=runtime_json_error,json=runtimeJsonError,proto3" json:"runtime_json_error,omitempty"`
	RuntimeConfig        *AgentRuntimeConfig    `protobuf:"bytes,12,opt,name=runtime_config,json=runtimeConfig,proto3" json:"runtime_config,omitempty"`
	SessionJsonlExists   bool                   `protobuf:"varint,13,opt,name=session_jsonl_exists,json=sessionJsonlExists,proto3" json:"session_jsonl_exists,omitempty"`
	SessionTurnCount     int32                  `protobuf:"varint,14,opt,name=session_turn_count,json=sessionTurnCount,proto3" json:"session_turn_count,omitempty"`
	SessionCorruptLines  int32                  `protobuf:"varint,15,opt,name=session_corrupt_lines,json=sessionCorruptLines,proto3" json:"session_corrupt_lines,omitempty"`
	AllowedAgentsExists  bool                   `protobuf:"varint,16,opt,name=allowed_agents_exists,json=allowedAgentsExists,proto3" json:"allowed_agents_exists,omitempty"`
	AllowedAgents        []string               `protobuf:"bytes,17,rep,name=allowed_agents,json=allowedAgents,proto3" json:"allowed_agents,omitempty"`
	ToolsDirExists       bool                   `protobuf:"varint,18,opt,name=tools_dir_exists,json=toolsDirExists,proto3" json:"tools_dir_exists,omitempty"`
	DiscoveredTools      []string               `protobuf:"bytes,19,rep,name=discovered_tools,json=discoveredTools,proto3" json:"discovered_tools,omitempty"`
	ShadowedTools        []string               `protobuf:"bytes,20,rep,name=shadowed_tools,json=shadowedTools,proto3" json:"shadowed_tools,omitempty"`
	SkillsDirExists      bool                   `protobuf:"varint,21,opt,name=skills_dir_exists,json=skillsDirExists,proto3" json:"skills_dir_exists,omitempty"`
	DiscoveredSkills     []string               `protobuf:"bytes,22,rep,name=discovered_skills,json=discoveredSkills,proto3" json:"discovered_skills,omitempty"`
	ShadowedSkills       []string               `protobuf:"bytes,23,rep,name=shadowed_skills,json=shadowedSkills,proto3" json:"shadowed_skills,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InspectAgentResponse) Reset() {
	*x = InspectAgentResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectAgentResponse) ProtoMessage() {}

func (x *InspectAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectAgentResponse.ProtoReflect.Descriptor instead.
func (*InspectAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *InspectAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InspectAgentResponse) GetAgentDir() string {
	if x != nil {
		return x.AgentDir
	}
	return ""
}

func (x *InspectAgentResponse) GetAgentDirExists() bool {
	if x != nil {
		return x.AgentDirExists
	}
	return false
}

func (x *InspectAgentResponse) GetAgentsMdExists() bool {
	if x != nil {
		return x.AgentsMdExists
	}
	return false
}

func (x *InspectAgentResponse) GetMemoryMdExists() bool {
	if x != nil {
		return x.MemoryMdExists
	}
	return false
}

func (x *InspectAgentResponse) GetDotEnvExists() bool {
	if x != nil {
		return x.DotEnvExists
	}
	return false
}

func (x *InspectAgentResponse) GetRuntimeJsonExists() bool {
	if x != nil {
		return x.RuntimeJsonExists
	}
	return false
}

func (x *InspectAgentResponse) GetRuntimeJsonIsSymlink() bool {
	if x != nil {
		return x.RuntimeJsonIsSymlink
	}
	return false
}

func (x *InspectAgentResponse) GetRuntimeJsonResolved() string {
	if x != nil {
		return x.RuntimeJsonResolved
	}
	return ""
}

func (x *InspectAgentResponse) GetRuntimeJsonValid() bool {
	if x != nil {
		return x.RuntimeJsonValid
	}
	return false
}

func (x *InspectAgentResponse) GetRuntimeJsonError() string {
	if x != nil {
		return x.RuntimeJsonError
	}
	return ""
}

func (x *InspectAgentResponse) GetRuntimeConfig() *AgentRuntimeConfig {
	if x != nil {
		return x.RuntimeConfig
	}
	return nil
}

func (x *InspectAgentResponse) GetSessionJsonlExists() bool {
	if x != nil {
		return x.SessionJsonlExists
	}
	return false
}

func (x *InspectAgentResponse) GetSessionTurnCount() int32 {
	if x != nil {
		return x.SessionTurnCount
	}
	return 0
}

func (x *InspectAgentResponse) GetSessionCorruptLines() int32 {
	if x != nil {
		return x.SessionCorruptLines
	}
	return 0
}

func (x *InspectAgentResponse) GetAllowedAgentsExists() bool {
	if x != nil {
		return x.AllowedAgentsExists
	}
	return false
}

func (x *InspectAgentResponse) GetAllowedAgents() []string {
	if x != nil {
		return x.AllowedAgents
	}
	return nil
}

func (x *InspectAgentResponse) GetToolsDirExists() bool {
	if x != nil {
		return x.ToolsDirExists
	}
	return false
}

func (x *InspectAgentResponse) GetDiscoveredTools() []string {
	if x != nil {
		return x.DiscoveredTools
	}
	return nil
}

func (x *InspectAgentResponse) GetShadowedTools() []string {
	if x != nil {
		return x.ShadowedTools
	}
	return nil
}

func (x *InspectAgentResponse) GetSkillsDirExists() bool {
	if x != nil {
		return x.SkillsDirExists
	}
	return false
}

func (x *InspectAgentResponse) GetDiscoveredSkills() []string {
	if x != nil {
		return x.DiscoveredSkills
	}
	return nil
}

func (x *InspectAgentResponse) GetShadowedSkills() []string {
	if x != nil {
		return x.ShadowedSkills
	}
	return nil
}

// AgentRuntimeConfig represents parsed runtime.json configuration.
type AgentRuntimeConfig struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Provider                      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Endpoint                      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Model                         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey                        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ContextWindow                 int32                  `protobuf:"varint,5,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	TimeoutSeconds                int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	AnthropicThinkingBudgetTokens *int32                 `protobuf:"varint,7,opt,name=anthropic_thinking_budget_tokens,json=anthropicThinkingBudgetTokens,proto3,oneof" json:"anthropic_thinking_budget_tokens,omitempty"`
	AnthropicThinkingEffort       string                 `protobuf:"bytes,8,opt,name=anthropic_thinking_effort,json=anthropicThinkingEffort,proto3" json:"anthropic_thinking_effort,omitempty"`
	AnthropicThinkingMode         string                 `protobuf:"bytes,9,opt,name=anthropic_thinking_mode,json=anthropicThinkingMode,proto3" json:"anthropic_thinking_mode,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *AgentRuntimeConfig) Reset() {
	*x = AgentRuntimeConfig{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRuntimeConfig) ProtoMessage() {}

func (x *AgentRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRuntimeConfig.ProtoReflect.Descriptor instead.
func (*AgentRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentRuntimeConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentRuntimeConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AgentRuntimeConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentRuntimeConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AgentRuntimeConfig) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *AgentRuntimeConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *AgentRuntimeConfig) GetAnthropicThinkingBudgetTokens() int32 {
	if x != nil && x.AnthropicThinkingBudgetTokens != nil {
		return *x.AnthropicThinkingBudgetTokens
	}
	return 0
}

func (x *AgentRuntimeConfig) GetAnthropicThinkingEffort() string {
	if x != nil {
		return x.AnthropicThinkingEffort
	}
	return ""
}

func (x *AgentRuntimeConfig) GetAnthropicThinkingMode() string {
	if x != nil {
		return x.AnthropicThinkingMode
	}
	return ""
}

// ReadSessionRequest specifies parameters for reading an agent's session turns.
type ReadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorkspaceDir  string                 `protobuf:"bytes,2,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionRequest) Reset() {
	*x = ReadSessionRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionRequest) ProtoMessage() {}

func (x *ReadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionRequest.ProtoReflect.Descriptor instead.
func (*ReadSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ReadSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReadSessionRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

// ReadSessionResponse contains the parsed turns of an agent session.
type ReadSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turns         []*SessionTurn         `protobuf:"bytes,1,rep,name=turns,proto3" json:"turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSessionResponse) Reset() {
	*x = ReadSessionResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSessionResponse) ProtoMessage() {}

func (x *ReadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSessionResponse.ProtoReflect.Descriptor instead.
func (*ReadSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ReadSessionResponse) GetTurns() []*SessionTurn {
	if x != nil {
		return x.Turns
	}
	return nil
}

// SessionTurn represents a single conversational turn in session.jsonl.
type SessionTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Parts         []*SessionPart         `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTurn) Reset() {
	*x = SessionTurn{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTurn) ProtoMessage() {}

func (x *SessionTurn) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTurn.ProtoReflect.Descriptor instead.
func (*SessionTurn) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SessionTurn) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionTurn) GetParts() []*SessionPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// SessionPart represents one part of a turn (text or inline data).
//
// NOTE(D112 v1): SessionPart currently models plain text and inline data parts.
// Non-text parts such as tool invocations (FunctionCall and FunctionResponse)
// stored in session.jsonl are omitted during conversion in v1. This lossy
// conversion is accepted for v1; this protobuf interface is canonical going forward
// and richer part schemas may be introduced in a future revision.
type SessionPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	InlineData    []byte                 `protobuf:"bytes,2,opt,name=inline_data,json=inlineData,proto3" json:"inline_data,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionPart) Reset() {
	*x = SessionPart{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPart) ProtoMessage() {}

func (x *SessionPart) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPart.ProtoReflect.Descriptor instead.
func (*SessionPart) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SessionPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SessionPart) GetInlineData() []byte {
	if x != nil {
		return x.InlineData
	}
	return nil
}

func (x *SessionPart) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// ReadMemoryRequest specifies parameters for reading an agent's memory.
type ReadMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorkspaceDir  string                 `protobuf:"bytes,2,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMemoryRequest) Reset() {
	*x = ReadMemoryRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMemoryRequest) ProtoMessage() {}

func (x *ReadMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMemoryRequest.ProtoReflect.Descriptor instead.
func (*ReadMemoryRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ReadMemoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReadMemoryRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

// ReadMemoryResponse contains the memory markdown content.
type ReadMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryMd      string                 `protobuf:"bytes,1,opt,name=memory_md,json=memoryMd,proto3" json:"memory_md,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMemoryResponse) Reset() {
	*x = ReadMemoryResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMemoryResponse) ProtoMessage() {}

func (x *ReadMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMemoryResponse.ProtoReflect.Descriptor instead.
func (*ReadMemoryResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ReadMemoryResponse) GetMemoryMd() string {
	if x != nil {
		return x.MemoryMd
	}
	return ""
}

// RenderSystemPromptRequest specifies parameters for rendering an agent's prompt.
type RenderSystemPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorkspaceDir  string                 `protobuf:"bytes,2,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderSystemPromptRequest) Reset() {
	*x = RenderSystemPromptRequest{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSystemPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSystemPromptRequest) ProtoMessage() {}

func (x *RenderSystemPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSystemPromptRequest.ProtoReflect.Descriptor instead.
func (*RenderSystemPromptRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RenderSystemPromptRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RenderSystemPromptRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

// RenderSystemPromptResponse contains the rendered prompt string.
type RenderSystemPromptResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RenderedPrompt string                 `protobuf:"bytes,1,opt,name=rendered_prompt,json=renderedPrompt,proto3" json:"rendered_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenderSystemPromptResponse) Reset() {
	*x = RenderSystemPromptResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSystemPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSystemPromptResponse) ProtoMessage() {}

func (x *RenderSystemPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSystemPromptResponse.ProtoReflect.Descriptor instead.
func (*RenderSystemPromptResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RenderSystemPromptResponse) GetRenderedPrompt() string {
	if x != nil {
		return x.RenderedPrompt
	}
	return ""
}

// InspectSessionContextRequest specifies parameters for inspecting session context.
type InspectSessionContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorkspaceDir  string                 `protobuf:"bytes,2,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectSessionContextRequest) Reset() {
	*x = InspectSessionContextRequest{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectSessionContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectSessionContextRequest) ProtoMessage() {}

func (x *InspectSessionContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectSessionContextRequest.ProtoReflect.Descriptor instead.
func (*InspectSessionContextRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *InspectSessionContextRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InspectSessionContextRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

// InspectSessionContextResponse contains context window and token usage estimates.
type InspectSessionContextResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AgentId               string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Model                 string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ContextWindow         int32                  `protobuf:"varint,3,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	CompactionThreshold   int32                  `protobuf:"varint,4,opt,name=compaction_threshold,json=compactionThreshold,proto3" json:"compaction_threshold,omitempty"`
	CompactionOverheadPct float64                `protobuf:"fixed64,5,opt,name=compaction_overhead_pct,json=compactionOverheadPct,proto3" json:"compaction_overhead_pct,omitempty"`
	EstimatedTotalTokens  int32                  `protobuf:"varint,6,opt,name=estimated_total_tokens,json=estimatedTotalTokens,proto3" json:"estimated_total_tokens,omitempty"`
	SessionTurnsTokens    int32                  `protobuf:"varint,7,opt,name=session_turns_tokens,json=sessionTurnsTokens,proto3" json:"session_turns_tokens,omitempty"`
	PromptTokensEstimate  int32                  `protobuf:"varint,8,opt,name=prompt_tokens_estimate,json=promptTokensEstimate,proto3" json:"prompt_tokens_estimate,omitempty"`
	MemoryTokensEstimate  int32                  `protobuf:"varint,9,opt,name=memory_tokens_estimate,json=memoryTokensEstimate,proto3" json:"memory_tokens_estimate,omitempty"`
	PercentToThreshold    float64                `protobuf:"fixed64,10,opt,name=percent_to_threshold,json=percentToThreshold,proto3" json:"percent_to_threshold,omitempty"`
	PercentToWindow       float64                `protobuf:"fixed64,11,opt,name=percent_to_window,json=percentToWindow,proto3" json:"percent_to_window,omitempty"`
	TurnCount             int32                  `protobuf:"varint,12,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	Compacted             bool                   `protobuf:"varint,13,opt,name=compacted,proto3" json:"compacted,omitempty"`
	LastPromptTokens      int32                  `protobuf:"varint,14,opt,name=last_prompt_tokens,json=lastPromptTokens,proto3" json:"last_prompt_tokens,omitempty"`
	LastCandidatesTokens  int32                  `protobuf:"varint,15,opt,name=last_candidates_tokens,json=lastCandidatesTokens,proto3" json:"last_candidates_tokens,omitempty"`
	LastTotalTokens       int32                  `protobuf:"varint,16,opt,name=last_total_tokens,json=lastTotalTokens,proto3" json:"last_total_tokens,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InspectSessionContextResponse) Reset() {
	*x = InspectSessionContextResponse{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectSessionContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectSessionContextResponse) ProtoMessage() {}

func (x *InspectSessionContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectSessionContextResponse.ProtoReflect.Descriptor instead.
func (*InspectSessionContextResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *InspectSessionContextResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InspectSessionContextResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *InspectSessionContextResponse) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *InspectSessionContextResponse) GetCompactionThreshold() int32 {
	if x != nil {
		return x.CompactionThreshold
	}
	return 0
}

func (x *InspectSessionContextResponse) GetCompactionOverheadPct() float64 {
	if x != nil {
		return x.CompactionOverheadPct
	}
	return 0
}

func (x *InspectSessionContextResponse) GetEstimatedTotalTokens() int32 {
	if x != nil {
		return x.EstimatedTotalTokens
	}
	return 0
}

func (x *InspectSessionContextResponse) GetSessionTurnsTokens() int32 {
	if x != nil {
		return x.SessionTurnsTokens
	}
	return 0
}

func (x *InspectSessionContextResponse) GetPromptTokensEstimate() int32 {
	if x != nil {
		return x.PromptTokensEstimate
	}
	return 0
}

func (x *InspectSessionContextResponse) GetMemoryTokensEstimate() int32 {
	if x != nil {
		return x.MemoryTokensEstimate
	}
	return 0
}

func (x *InspectSessionContextResponse) GetPercentToThreshold() float64 {
	if x != nil {
		return x.PercentToThreshold
	}
	return 0
}

func (x *InspectSessionContextResponse) GetPercentToWindow() float64 {
	if x != nil {
		return x.PercentToWindow
	}
	return 0
}

func (x *InspectSessionContextResponse) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *InspectSessionContextResponse) GetCompacted() bool {
	if x != nil {
		return x.Compacted
	}
	return false
}

func (x *InspectSessionContextResponse) GetLastPromptTokens() int32 {
	if x != nil {
		return x.LastPromptTokens
	}
	return 0
}

func (x *InspectSessionContextResponse) GetLastCandidatesTokens() int32 {
	if x != nil {
		return x.LastCandidatesTokens
	}
	return 0
}

func (x *InspectSessionContextResponse) GetLastTotalTokens() int32 {
	if x != nil {
		return x.LastTotalTokens
	}
	return 0
}

// InspectAgentLocksRequest specifies parameters for inspecting workspace agent locks.
type InspectAgentLocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceDir  string                 `protobuf:"bytes,1,opt,name=workspace_dir,json=workspaceDir,proto3" json:"workspace_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectAgentLocksRequest) Reset() {
	*x = InspectAgentLocksRequest{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectAgentLocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectAgentLocksRequest) ProtoMessage() {}

func (x *InspectAgentLocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectAgentLocksRequest.ProtoReflect.Descriptor instead.
func (*InspectAgentLocksRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *InspectAgentLocksRequest) GetWorkspaceDir() string {
	if x != nil {
		return x.WorkspaceDir
	}
	return ""
}

// InspectAgentLocksResponse contains lock observations for agents in the workspace.
type InspectAgentLocksResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Observations  []*AgentLockObservation `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectAgentLocksResponse) Reset() {
	*x = InspectAgentLocksResponse{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectAgentLocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectAgentLocksResponse) ProtoMessage() {}

func (x *InspectAgentLocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectAgentLocksResponse.ProtoReflect.Descriptor instead.
func (*InspectAgentLocksResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *InspectAgentLocksResponse) GetObservations() []*AgentLockObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

// AgentLockObservation captures session lock status and activity for an agent.
type AgentLockObservation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentDir       string                 `protobuf:"bytes,2,opt,name=agent_dir,json=agentDir,proto3" json:"agent_dir,omitempty"`
	LockExists     bool                   `protobuf:"varint,3,opt,name=lock_exists,json=lockExists,proto3" json:"lock_exists,omitempty"`
	HolderPid      int32                  `protobuf:"varint,4,opt,name=holder_pid,json=holderPid,proto3" json:"holder_pid,omitempty"`
	HolderPidValid bool                   `protobuf:"varint,5,opt,name=holder_pid_valid,json=holderPidValid,proto3" json:"holder_pid_valid,omitempty"`
	HolderAlive    bool                   `protobuf:"varint,6,opt,name=holder_alive,json=holderAlive,proto3" json:"holder_alive,omitempty"`
	HolderCommand  string                 `protobuf:"bytes,7,opt,name=holder_command,json=holderCommand,proto3" json:"holder_command,omitempty"`
	LockHeldSince  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=lock_held_since,json=lockHeldSince,proto3" json:"lock_held_since,omitempty"`
	SessionExists  bool                   `protobuf:"varint,9,opt,name=session_exists,json=sessionExists,proto3" json:"session_exists,omitempty"`
	LastWrite      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_write,json=lastWrite,proto3" json:"last_write,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentLockObservation) Reset() {
	*x = AgentLockObservation{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentLockObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentLockObservation) ProtoMessage() {}

func (x *AgentLockObservation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentLockObservation.ProtoReflect.Descriptor instead.
func (*AgentLockObservation) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *AgentLockObservation) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentLockObservation) GetAgentDir() string {
	if x != nil {
		return x.AgentDir
	}
	return ""
}

func (x *AgentLockObservation) GetLockExists() bool {
	if x != nil {
		return x.LockExists
	}
	return false
}

func (x *AgentLockObservation) GetHolderPid() int32 {
	if x != nil {
		return x.HolderPid
	}
	return 0
}

func (x *AgentLockObservation) GetHolderPidValid() bool {
	if x != nil {
		return x.HolderPidValid
	}
	return false
}

func (x *AgentLockObservation) GetHolderAlive() bool {
	if x != nil {
		return x.HolderAlive
	}
	return false
}

func (x *AgentLockObservation) GetHolderCommand() string {
	if x != nil {
		return x.HolderCommand
	}
	return ""
}

func (x *AgentLockObservation) GetLockHeldSince() *timestamppb.Timestamp {
	if x != nil {
		return x.LockHeldSince
	}
	return nil
}

func (x *AgentLockObservation) GetSessionExists() bool {
	if x != nil {
		return x.SessionExists
	}
	return false
}

func (x *AgentLockObservation) GetLastWrite() *timestamppb.Timestamp {
	if x != nil {
		return x.LastWrite
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x11wackypub.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x11ListAgentsRequest\x12#\n" +
	"\rworkspace_dir\x18\x01 \x01(\tR\fworkspaceDir\"1\n" +
	"\x12ListAgentsResponse\x12\x1b\n" +
	"\tagent_ids\x18\x01 \x03(\tR\bagentIds\"U\n" +
	"\x13InspectAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rworkspace_dir\x18\x02 \x01(\tR\fworkspaceDir\"\xa4\b\n" +
	"\x14InspectAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_dir\x18\x02 \x01(\tR\bagentDir\x12(\n" +
	"\x10agent_dir_exists\x18\x03 \x01(\bR\x0eagentDirExists\x12(\n" +
	"\x10agents_md_exists\x18\x04 \x01(\bR\x0eagentsMdExists\x12(\n" +
	"\x10memory_md_exists\x18\x05 \x01(\bR\x0ememoryMdExists\x12$\n" +
	"\x0edot_env_exists\x18\x06 \x01(\bR\fdotEnvExists\x12.\n" +
	"\x13runtime_json_exists\x18\a \x01(\bR\x11runtimeJsonExists\x125\n" +
	"\x17runtime_json_is_symlink\x18\b \x01(\bR\x14runtimeJsonIsSymlink\x122\n" +
	"\x15runtime_json_resolved\x18\t \x01(\tR\x13runtimeJsonResolved\x12,\n" +
	"\x12runtime_json_valid\x18\n" +
	" \x01(\bR\x10runtimeJsonValid\x12,\n" +
	"\x12runtime_json_error\x18\v \x01(\tR\x10runtimeJsonError\x12L\n" +
	"\x0eruntime_config\x18\f \x01(\v2%.wackypub.agent.v1.AgentRuntimeConfigR\rruntimeConfig\x120\n" +
	"\x14session_jsonl_exists\x18\r \x01(\bR\x12sessionJsonlExists\x12,\n" +
	"\x12session_turn_count\x18\x0e \x01(\x05R\x10sessionTurnCount\x122\n" +
	"\x15session_corrupt_lines\x18\x0f \x01(\x05R\x13sessionCorruptLines\x122\n" +
	"\x15allowed_agents_exists\x18\x10 \x01(\bR\x13allowedAgentsExists\x12%\n" +
	"\x0eallowed_agents\x18\x11 \x03(\tR\rallowedAgents\x12(\n" +
	"\x10tools_dir_exists\x18\x12 \x01(\bR\x0etoolsDirExists\x12)\n" +
	"\x10discovered_tools\x18\x13 \x03(\tR\x0fdiscoveredTools\x12%\n" +
	"\x0eshadowed_tools\x18\x14 \x03(\tR\rshadowedTools\x12*\n" +
	"\x11skills_dir_exists\x18\x15 \x01(\bR\x0fskillsDirExists\x12+\n" +
	"\x11discovered_skills\x18\x16 \x03(\tR\x10discoveredSkills\x12'\n" +
	"\x0fshadowed_skills\x18\x17 \x03(\tR\x0eshadowedSkills\"\xb2\x03\n" +
	"\x12AgentRuntimeConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12%\n" +
	"\x0econtext_window\x18\x05 \x01(\x05R\rcontextWindow\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12L\n" +
	" anthropic_thinking_budget_tokens\x18\a \x01(\x05H\x00R\x1danthropicThinkingBudgetTokens\x88\x01\x01\x12:\n" +
	"\x19anthropic_thinking_effort\x18\b \x01(\tR\x17anthropicThinkingEffort\x126\n" +
	"\x17anthropic_thinking_mode\x18\t \x01(\tR\x15anthropicThinkingModeB#\n" +
	"!_anthropic_thinking_budget_tokens\"T\n" +
	"\x12ReadSessionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rworkspace_dir\x18\x02 \x01(\tR\fworkspaceDir\"K\n" +
	"\x13ReadSessionResponse\x124\n" +
	"\x05turns\x18\x01 \x03(\v2\x1e.wackypub.agent.v1.SessionTurnR\x05turns\"W\n" +
	"\vSessionTurn\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x124\n" +
	"\x05parts\x18\x02 \x03(\v2\x1e.wackypub.agent.v1.SessionPartR\x05parts\"_\n" +
	"\vSessionPart\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vinline_data\x18\x02 \x01(\fR\n" +
	"inlineData\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"S\n" +
	"\x11ReadMemoryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rworkspace_dir\x18\x02 \x01(\tR\fworkspaceDir\"1\n" +
	"\x12ReadMemoryResponse\x12\x1b\n" +
	"\tmemory_md\x18\x01 \x01(\tR\bmemoryMd\"[\n" +
	"\x19RenderSystemPromptRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rworkspace_dir\x18\x02 \x01(\tR\fworkspaceDir\"E\n" +
	"\x1aRenderSystemPromptResponse\x12'\n" +
	"\x0frendered_prompt\x18\x01 \x01(\tR\x0erenderedPrompt\"^\n" +
	"\x1cInspectSessionContextRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rworkspace_dir\x18\x02 \x01(\tR\fworkspaceDir\"\xe1\x05\n" +
	"\x1dInspectSessionContextResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12%\n" +
	"\x0econtext_window\x18\x03 \x01(\x05R\rcontextWindow\x121\n" +
	"\x14compaction_threshold\x18\x04 \x01(\x05R\x13compactionThreshold\x126\n" +
	"\x17compaction_overhead_pct\x18\x05 \x01(\x01R\x15compactionOverheadPct\x124\n" +
	"\x16estimated_total_tokens\x18\x06 \x01(\x05R\x14estimatedTotalTokens\x120\n" +
	"\x14session_turns_tokens\x18\a \x01(\x05R\x12sessionTurnsTokens\x124\n" +
	"\x16prompt_tokens_estimate\x18\b \x01(\x05R\x14promptTokensEstimate\x124\n" +
	"\x16memory_tokens_estimate\x18\t \x01(\x05R\x14memoryTokensEstimate\x120\n" +
	"\x14percent_to_threshold\x18\n" +
	" \x01(\x01R\x12percentToThreshold\x12*\n" +
	"\x11percent_to_window\x18\v \x01(\x01R\x0fpercentToWindow\x12\x1d\n" +
	"\n" +
	"turn_count\x18\f \x01(\x05R\tturnCount\x12\x1c\n" +
	"\tcompacted\x18\r \x01(\bR\tcompacted\x12,\n" +
	"\x12last_prompt_tokens\x18\x0e \x01(\x05R\x10lastPromptTokens\x124\n" +
	"\x16last_candidates_tokens\x18\x0f \x01(\x05R\x14lastCandidatesTokens\x12*\n" +
	"\x11last_total_tokens\x18\x10 \x01(\x05R\x0flastTotalTokens\"?\n" +
	"\x18InspectAgentLocksRequest\x12#\n" +
	"\rworkspace_dir\x18\x01 \x01(\tR\fworkspaceDir\"h\n" +
	"\x19InspectAgentLocksResponse\x12K\n" +
	"\fobservations\x18\x01 \x03(\v2'.wackypub.agent.v1.AgentLockObservationR\fobservations\"\xa8\x03\n" +
	"\x14AgentLockObservation\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_dir\x18\x02 \x01(\tR\bagentDir\x12\x1f\n" +
	"\vlock_exists\x18\x03 \x01(\bR\n" +
	"lockExists\x12\x1d\n" +
	"\n" +
	"holder_pid\x18\x04 \x01(\x05R\tholderPid\x12(\n" +
	"\x10holder_pid_valid\x18\x05 \x01(\bR\x0eholderPidValid\x12!\n" +
	"\fholder_alive\x18\x06 \x01(\bR\vholderAlive\x12%\n" +
	"\x0eholder_command\x18\a \x01(\tR\rholderCommand\x12B\n" +
	"\x0flock_held_since\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rlockHeldSince\x12%\n" +
	"\x0esession_exists\x18\t \x01(\bR\rsessionExists\x129\n" +
	"\n" +
	"last_write\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tlastWrite2\xe2\x05\n" +
	"\fAgentService\x12Y\n" +
	"\n" +
	"ListAgents\x12$.wackypub.agent.v1.ListAgentsRequest\x1a%.wackypub.agent.v1.ListAgentsResponse\x12_\n" +
	"\fInspectAgent\x12&.wackypub.agent.v1.InspectAgentRequest\x1a'.wackypub.agent.v1.InspectAgentResponse\x12\\\n" +
	"\vReadSession\x12%.wackypub.agent.v1.ReadSessionRequest\x1a&.wackypub.agent.v1.ReadSessionResponse\x12Y\n" +
	"\n" +
	"ReadMemory\x12$.wackypub.agent.v1.ReadMemoryRequest\x1a%.wackypub.agent.v1.ReadMemoryResponse\x12q\n" +
	"\x12RenderSystemPrompt\x12,.wackypub.agent.v1.RenderSystemPromptRequest\x1a-.wackypub.agent.v1.RenderSystemPromptResponse\x12z\n" +
	"\x15InspectSessionContext\x12/.wackypub.agent.v1.InspectSessionContextRequest\x1a0.wackypub.agent.v1.InspectSessionContextResponse\x12n\n" +
	"\x11InspectAgentLocks\x12+.wackypub.agent.v1.InspectAgentLocksRequest\x1a,.wackypub.agent.v1.InspectAgentLocksResponseB7Z5github.com/colinrgodsey/wackypub/pkg/agent/v1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_agent_proto_goTypes = []any{
	(*ListAgentsRequest)(nil),             // 0: wackypub.agent.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),            // 1: wackypub.agent.v1.ListAgentsResponse
	(*InspectAgentRequest)(nil),           // 2: wackypub.agent.v1.InspectAgentRequest
	(*InspectAgentResponse)(nil),          // 3: wackypub.agent.v1.InspectAgentResponse
	(*AgentRuntimeConfig)(nil),            // 4: wackypub.agent.v1.AgentRuntimeConfig
	(*ReadSessionRequest)(nil),            // 5: wackypub.agent.v1.ReadSessionRequest
	(*ReadSessionResponse)(nil),           // 6: wackypub.agent.v1.ReadSessionResponse
	(*SessionTurn)(nil),                   // 7: wackypub.agent.v1.SessionTurn
	(*SessionPart)(nil),                   // 8: wackypub.agent.v1.SessionPart
	(*ReadMemoryRequest)(nil),             // 9: wackypub.agent.v1.ReadMemoryRequest
	(*ReadMemoryResponse)(nil),            // 10: wackypub.agent.v1.ReadMemoryResponse
	(*RenderSystemPromptRequest)(nil),     // 11: wackypub.agent.v1.RenderSystemPromptRequest
	(*RenderSystemPromptResponse)(nil),    // 12: wackypub.agent.v1.RenderSystemPromptResponse
	(*InspectSessionContextRequest)(nil),  // 13: wackypub.agent.v1.InspectSessionContextRequest
	(*InspectSessionContextResponse)(nil), // 14: wackypub.agent.v1.InspectSessionContextResponse
	(*InspectAgentLocksRequest)(nil),      // 15: wackypub.agent.v1.InspectAgentLocksRequest
	(*InspectAgentLocksResponse)(nil),     // 16: wackypub.agent.v1.InspectAgentLocksResponse
	(*AgentLockObservation)(nil),          // 17: wackypub.agent.v1.AgentLockObservation
	(*timestamppb.Timestamp)(nil),         // 18: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: wackypub.agent.v1.InspectAgentResponse.runtime_config:type_name -> wackypub.agent.v1.AgentRuntimeConfig
	7,  // 1: wackypub.agent.v1.ReadSessionResponse.turns:type_name -> wackypub.agent.v1.SessionTurn
	8,  // 2: wackypub.agent.v1.SessionTurn.parts:type_name -> wackypub.agent.v1.SessionPart
	17, // 3: wackypub.agent.v1.InspectAgentLocksResponse.observations:type_name -> wackypub.agent.v1.AgentLockObservation
	18, // 4: wackypub.agent.v1.AgentLockObservation.lock_held_since:type_name -> google.protobuf.Timestamp
	18, // 5: wackypub.agent.v1.AgentLockObservation.last_write:type_name -> google.protobuf.Timestamp
	0,  // 6: wackypub.agent.v1.AgentService.ListAgents:input_type -> wackypub.agent.v1.ListAgentsRequest
	2,  // 7: wackypub.agent.v1.AgentService.InspectAgent:input_type -> wackypub.agent.v1.InspectAgentRequest
	5,  // 8: wackypub.agent.v1.AgentService.ReadSession:input_type -> wackypub.agent.v1.ReadSessionRequest
	9,  // 9: wackypub.agent.v1.AgentService.ReadMemory:input_type -> wackypub.agent.v1.ReadMemoryRequest
	11, // 10: wackypub.agent.v1.AgentService.RenderSystemPrompt:input_type -> wackypub.agent.v1.RenderSystemPromptRequest
	13, // 11: wackypub.agent.v1.AgentService.InspectSessionContext:input_type -> wackypub.agent.v1.InspectSessionContextRequest
	15, // 12: wackypub.agent.v1.AgentService.InspectAgentLocks:input_type -> wackypub.agent.v1.InspectAgentLocksRequest
	1,  // 13: wackypub.agent.v1.AgentService.ListAgents:output_type -> wackypub.agent.v1.ListAgentsResponse
	3,  // 14: wackypub.agent.v1.AgentService.InspectAgent:output_type -> wackypub.agent.v1.InspectAgentResponse
	6,  // 15: wackypub.agent.v1.AgentService.ReadSession:output_type -> wackypub.agent.v1.ReadSessionResponse
	10, // 16: wackypub.agent.v1.AgentService.ReadMemory:output_type -> wackypub.agent.v1.ReadMemoryResponse
	12, // 17: wackypub.agent.v1.AgentService.RenderSystemPrompt:output_type -> wackypub.agent.v1.RenderSystemPromptResponse
	14, // 18: wackypub.agent.v1.AgentService.InspectSessionContext:output_type -> wackypub.agent.v1.InspectSessionContextResponse
	16, // 19: wackypub.agent.v1.AgentService.InspectAgentLocks:output_type -> wackypub.agent.v1.InspectAgentLocksResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
